### ISSUE TITLE
failed to open and extract

### ISSUE THREAD

**Issue by AntonioPinedaV** [MilosFDev/archive-extractor-password-list#1]
I tried this with four password files and returned the same error, could you help me?

C:\python archivepassword.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\xxx\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Antonio\Downloads\Telegram Desktop\archivepassword.py", line 37, in extract_button_click
    if extract_7z_archive(archive_path, password):
  File "C:\Users\Antonio\Downloads\Telegram Desktop\archivepassword.py", line 11, in extract_7z_archive
    szf.extractall()
  File "C:\xxx\Python310\lib\site-packages\py7zr\py7zr.py", line 963, in extract all
    self._extract(path=path, return_dict=False, callback=callback)
  File "C:\xxx\Python310\lib\site-packages\py7zr\py7zr.py", line 624, in _extract
    self.worker.extract(
  File "C:\xxx\Python310\lib\site-packages\py7zr\py7zr.py", line 1204, in extract
    self.extract_single(
  File "C:\xxx\Python310\lib\site-packages\py7zr\py7zr.py", line 1292, in extract_single
    raise e
  File "C:\xxx\Python310\lib\site-packages\py7zr\py7zr.py", line 1289, in extract_single
    self._extract_single(fp, files, path, src_end, q, skip_notarget)
  File "C:\xxx\Python310\lib\site-packages\py7zr\py7zr.py", line 1358, in _extract_single
    crc32 = self.decompress(fp, f.folder, obfp, f.uncompressed, f.compressed, src_end)
  File "C:\xxx\Python310\lib\site-packages\py7zr\py7zr.py", line 1413, in decompress
    tmp = decompressor.decompress(fp, min(out_remaining, max_block_size))
  File "C:\xxx\Python310\lib\site-packages\py7zr\compressor.py", line 697, in decompress
    tmp = self._decompress(data, max_length)
  File "C:\xxx\Python310\lib\site-packages\py7zr\compressor.py", line 653, in _decompress
    data = decompressor.decompress(data, max_length)
_lzma.LZMAError: Corrupt input data

**Comment by MilosFDev** [comment]
Currently GUI version is having some problems, I will probably need to get CLI version back until I fix the issue
